<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accelerator.Core.Domain\Accelerator.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authors\Repositories\" />
    <Folder Include="Courses\Configs\" />
    <Folder Include="Courses\Repositories\" />
  </ItemGroup>

</Project>
