<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Courses\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accelerator.Core.Domain\Accelerator.Core.Domain.csproj" />
    <ProjectReference Include="..\Accelerator.Framework\Accelerator.Framework.csproj" />
  </ItemGroup>

</Project>
