<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Autors\Entities\" />
    <Folder Include="Autors\Commands\" />
    <Folder Include="Autors\Repositories\" />
    <Folder Include="Autors\Queries\" />
    <Folder Include="Courses\Entities\" />
    <Folder Include="Courses\Commands\" />
    <Folder Include="Courses\Repositories\" />
    <Folder Include="Courses\Queries\" />
  </ItemGroup>

</Project>
